default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: hotel_cms_development

test:
  <<: *default
  database: hotel_cms_test

production:
  <<: *default
  database: hotel_cms_production
  username: hotel_cms
  password: <%= ENV.fetch("HOTEL_CMS_DATABASE_PASSWORD", "") %>